### ISSUE TITLE
Release a new version? 

### ISSUE THREAD

**Issue by XiangpengHao** [awslabs/shuttle#64]
Hi, first of all, thanks for the great project!

I try to use shuttle in one of my projects and it failed to resolve dependencies. The reason is that the version on crates.io pins its dependencies on minor versions. I noticed that it was fixed in [this commit](https://github.com/awslabs/shuttle/commit/d983ac0dad6968763a09b7f57fa4de0809a3f1b0), but the code is not released to crates.io.

Is it possible to release a new minor version to reflect the changes made to shuttle since last release?

**Comment by jamesbornholt** [comment]
We just release v0.1.0 in #65. Thanks!
